version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: artusfacturacion-db
    environment:
      MYSQL_ROOT_PASSWORD: "artus"
      MYSQL_DATABASE: Artus  
    volumes:
      - ./bd/Artus.sql:/docker-entrypoint-initdb.d/Artus.sql  # Cargar el SQL automáticamente
    ports:
      - "3306:3306"  
    networks:
      - app-network

  php:
    build:
      context: ./Public
      dockerfile: Dockerfile  
    container_name: artusfacturacion-php
    ports:
      - "8080:80"
    volumes:
    - ./Public:/var/www/html/Public
    - ./App:/var/www/html/App
    - ./bd:/var/www/html/bd
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: artusfacturacion-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./Public:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
